import { Keypair, PublicKey } from '@solana/web3.js';
import { TOKEN_PROGRAM_ID, TOKEN_2022_PROGRAM_ID, unpackAccount } from '@solana/spl-token';
import { CLMM_PROGRAM_ID, ClmmConfigLayout, PoolInfoLayout, PersonalPositionLayout, getPdaAmmConfigId, getPdaPoolId, getPdaPersonalPositionAddress, LiquidityMathUtil, TickUtil, TxVersion, ClmmInstrument } from '@raydium-io/raydium-sdk-v2';
import BN from 'bn.js';
import Decimal from 'decimal.js';
import { U64,U128,raw,raydium,account,mint,holding,txPlan,line,checkVault,canonicalRequest,tokenAccounts } from './raydium-common.mjs';
import { transferFee,grossForNet,ceilDiv,validateSlippage } from './raydium-cpmm/math.mjs';
const PROGRAM=CLMM_PROGRAM_ID,MIN_TICK=-443636,MAX_TICK=443636;
export function clmmRange(pool,parameters={}){const spacing=pool.tickSpacing;const range=[parameters.tickLowerIndex??Math.ceil(MIN_TICK/spacing)*spacing,parameters.tickUpperIndex??Math.floor(MAX_TICK/spacing)*spacing];if(range.some(t=>!Number.isInteger(t)||t<MIN_TICK||t>MAX_TICK||t%spacing!==0)||range[0]>=range[1])throw new Error('CLMM ticks must be ordered, within bounds, and aligned to tick spacing');return range;}
function retained(ctx,pool){const key=`raydium-clmm:position:${pool}`;if(!ctx.signers.has(key))ctx.signers.set(key,Keypair.generate());return ctx.signers.get(key);}
async function config(ctx,index){if(!Number.isInteger(index)||index<0||index>65535)throw new Error('configIndex must be a u16');const id=getPdaAmmConfigId(PROGRAM,index).publicKey;const data=await account(ctx,id,PROGRAM,'CLMM config',ClmmConfigLayout,'AmmConfig');if(data.index!==index||!data.tickSpacing)throw new Error('Invalid CLMM fee configuration');return{...data,id,fundOwner:data.fundOwner.toBase58(),description:''};}
async function state(ctx,address){const data=await account(ctx,address,PROGRAM,'CLMM pool',PoolInfoLayout,'PoolState');if(!getPdaPoolId(PROGRAM,data.configId,data.mintA,data.mintB).publicKey.equals(new PublicKey(address)))throw new Error('CLMM pool address does not match configuration and mints');const cfg=await account(ctx,data.configId,PROGRAM,'CLMM config',ClmmConfigLayout,'AmmConfig');if(cfg.tickSpacing!==data.tickSpacing)throw new Error('CLMM fee configuration differs from pool');const [a,b]=await Promise.all([mint(ctx,data.mintA),mint(ctx,data.mintB)]);if(a.decimals!==data.mintDecimalsA||b.decimals!==data.mintDecimalsB)throw new Error('CLMM mint decimals differ from pool');await Promise.all([checkVault(ctx,data.vaultA,a,address),checkVault(ctx,data.vaultB,b,address)]);return{data,a,b};}
async function position(ctx,address,pool){const data=await account(ctx,address,PROGRAM,'CLMM position',PersonalPositionLayout,'PersonalPositionState');if(!data.poolId.equals(new PublicKey(pool))||!getPdaPersonalPositionAddress(PROGRAM,data.nftMint).publicKey.equals(new PublicKey(address)))throw new Error('CLMM position identity does not match');const nft=await mint(ctx,data.nftMint);const tokenAccount=await holding(ctx,nft.address,nft.programId);if(!tokenAccount)throw new Error('Wallet does not own a spendable position NFT');return{data,tokenAccount};}
export function clmmAmounts(pool,mints,range,liquidity,slippageBps,add){validateSlippage(slippageBps);const value=LiquidityMathUtil.getAmountsForLiquidity(pool.sqrtPriceX64,TickUtil.getSqrtPriceAtTick(range[0]),TickUtil.getSqrtPriceAtTick(range[1]),new BN(liquidity.toString()),add);return[value.amountA,value.amountB].map((x,i)=>{const n=BigInt(x.toString());const expected=add?grossForNet(n,mints[i]):n-transferFee(n,mints[i]);const limit=add?grossForNet(ceilDiv(n*BigInt(10000+slippageBps),10000n),mints[i]):(n-transferFee(n,mints[i]))*BigInt(10000-slippageBps)/10000n;return{expected,limit};});}
function fit(pool,mints,range,request){if(request.liquidity)return raw(request.liquidity,'Liquidity',U128);const budgets=[request.amountA,request.amountB].map(x=>x==null?null:raw(x));if(budgets.every(x=>x===null))throw new Error('Provide a token budget or liquidity');let lo=1n,hi=U128,best=0n;while(lo<=hi){const mid=(lo+hi)/2n;let values;try{values=clmmAmounts(pool,mints,range,mid,request.slippageBps,true);}catch(e){if(/u64|overflow/i.test(e.message)){hi=mid-1n;continue;}throw e;}if(values.every((v,i)=>v.limit<=U64&&(budgets[i]===null||v.limit<=budgets[i]))){best=mid;lo=mid+1n;}else hi=mid-1n;}if(!best)throw new Error('Deposit budget is too small');return best;}
export const raydiumClmm={
 id:'raydium-clmm',programIds:[PROGRAM.toBase58()],capabilities:['initialize','add','remove'],
 parameters:{initialize:[{name:'configIndex',label:'Fee configuration index',type:'number',default:0},{name:'initialPrice',label:'Initial price (token B per token A)',type:'text',required:true}],add:[{name:'tickLowerIndex',label:'Lower canonical protocol tick (optional)',type:'number'},{name:'tickUpperIndex',label:'Upper canonical protocol tick (optional)',type:'number'},{name:'wrapSol',label:'Use native SOL for WSOL input',type:'boolean',default:false}],remove:[{name:'wrapSol',label:'Unwrap WSOL proceeds into SOL',type:'boolean',default:false}]},
 async positions(ctx,{pool}){const holdings=await Promise.all([TOKEN_PROGRAM_ID,TOKEN_2022_PROGRAM_ID].map(programId=>ctx.connection.getTokenAccountsByOwner(ctx.owner,{programId},'confirmed')));const found=[];for(const response of holdings)for(const{pubkey,account:info}of response.value){const token=unpackAccount(pubkey,info,info.owner);if(token.amount!==1n||token.isFrozen||!token.isInitialized)continue;const pda=getPdaPersonalPositionAddress(PROGRAM,token.mint).publicKey;const infoP=await ctx.connection.getAccountInfo(pda,'confirmed');if(!infoP||!infoP.owner.equals(PROGRAM)||infoP.data.length<PersonalPositionLayout.span)continue;const p=await account(ctx,pda,PROGRAM,'CLMM position',PersonalPositionLayout,'PersonalPositionState');if(!p.nftMint.equals(token.mint)||pool&&p.poolId.toBase58()!==pool)continue;const poolState=await state(ctx,p.poolId);found.push({venue:this.id,mintA:poolState.a.address,mintB:poolState.b.address,pool:p.poolId.toBase58(),position:pda.toBase58(),mint:p.nftMint.toBase58(),liquidity:p.liquidity.toString(),tickLowerIndex:p.tickLower,tickUpperIndex:p.tickUpper});}return found;},
 async quote(ctx,request){validateSlippage(request.slippageBps);if(request.operation==='initialize'){const cfg=await config(ctx,request.parameters?.configIndex??0);const [a,b]=await Promise.all([mint(ctx,request.mintA),mint(ctx,request.mintB)]);if(a.address===b.address)throw new Error('Pool mints must differ');const price=new Decimal(request.parameters?.initialPrice??'NaN');if(!price.isFinite()||price.lte(0))throw new Error('Provide a positive initialPrice');const sorted=[a,b].sort((x,y)=>Buffer.compare(new PublicKey(x.address).toBuffer(),new PublicKey(y.address).toBuffer()));const sortedPrice=sorted[0]===a?price:new Decimal(1).div(price);const sqrt=TickUtil.priceToSqrtPriceX64(sortedPrice,sorted[0].decimals,sorted[1].decimals);if(sqrt.lt(TickUtil.getSqrtPriceAtTick(MIN_TICK))||sqrt.gt(TickUtil.getSqrtPriceAtTick(MAX_TICK)))throw new Error('Initial price exceeds CLMM bounds');const pool=getPdaPoolId(PROGRAM,cfg.id,new PublicKey(sorted[0].address),new PublicKey(sorted[1].address)).publicKey;if(await ctx.connection.getAccountInfo(pool,'confirmed'))throw new Error('Pool already exists; add liquidity instead');return{pool:pool.toBase58(),mintA:sorted[0].address,mintB:sorted[1].address,slot:await ctx.connection.getSlot('confirmed'),amounts:[],details:{noTokenMovement:true},warnings:['This creates an empty CLMM pool. Add liquidity after confirmation. Account rent and network fees require SOL.']};}
 if(!['add','remove'].includes(request.operation))throw new Error('Unsupported CLMM operation');const s=await state(ctx,request.pool);request=canonicalRequest(request,s.a.address,s.b.address);const old=request.position?await position(ctx,request.position,request.pool):null,remove=request.operation==='remove';if(remove&&!old)throw new Error('Provide a position to remove liquidity');if((s.data.status&(remove?2:1))!==0)throw new Error('This liquidity operation is disabled by pool status');const range=old?[old.data.tickLower,old.data.tickUpper]:clmmRange(s.data,request.parameters);const liq=remove?raw(request.liquidity,'Liquidity',U128):fit(s.data,[s.a,s.b],range,request);if(remove&&liq>BigInt(old.data.liquidity.toString()))throw new Error('Liquidity exceeds position holdings');const values=clmmAmounts(s.data,[s.a,s.b],range,liq,request.slippageBps,!remove);if(values.some(x=>x.expected>U64||x.limit>U64)||values.every(x=>x.expected===0n))throw new Error('Liquidity produces zero or overflowing token amounts');const nft=old?.data.nftMint??retained(ctx,request.pool).publicKey;return{pool:request.pool,mintA:s.a.address,mintB:s.b.address,position:getPdaPersonalPositionAddress(PROGRAM,nft).publicKey.toBase58(),slot:await ctx.connection.getSlot('confirmed'),amounts:[line(s.a,values[0].expected,values[0].limit,remove?'credit':'debit'),line(s.b,values[1].expected,values[1].limit,remove?'credit':'debit')],details:{liquidity:liq.toString(),positionMint:nft.toBase58(),tickLowerIndex:range[0],tickUpperIndex:range[1]},warnings:remove?['The position remains open; this instruction also collects accrued fees and rewards.']:['Position and token-account rent is additional.']};
 },
 async build(ctx,request,quote){const ray=await raydium(ctx);if(request.operation==='initialize'){const cfg=await config(ctx,request.parameters?.configIndex??0),[a,b]=await Promise.all([mint(ctx,request.mintA),mint(ctx,request.mintB)]);const built=await ray.clmm.createPool({programId:PROGRAM,owner:ctx.owner,mint1:a,mint2:b,ammConfig:cfg,initialPrice:new Decimal(request.parameters.initialPrice),txVersion:TxVersion.LEGACY});if(String(built.extInfo.address.id)!==quote.pool)throw new Error('CLMM pool identity changed');return{pool:quote.pool,transactions:[txPlan(built)]};}
 const s=await state(ctx,quote.pool);
 // LP instructions only require the validated pool/config/vault identities. The
 // SDK swap-info fetch assumes tick arrays already exist and fails on a newly
 // initialized empty pool, before its first position can create those arrays.
 const poolInfo={id:quote.pool,programId:PROGRAM.toBase58(),mintA:s.a,mintB:s.b,config:{id:s.data.configId.toBase58(),tickSpacing:s.data.tickSpacing}};
 const rewardInfos=await Promise.all(s.data.rewardInfos.filter(r=>!r.mint.equals(PublicKey.default)&&!r.vault.equals(PublicKey.default)).map(async r=>({mint:await mint(ctx,r.mint),vault:r.vault.toBase58()})));
 const data={poolInfo,poolKeys:{...poolInfo,vault:{A:s.data.vaultA.toBase58(),B:s.data.vaultB.toBase58()},rewardInfos}};
 const remove=request.operation==='remove',limits=[s.a,s.b].map(m=>new BN(quote.amounts.find(a=>a.mint===m.address).limitRaw));
 const accounts=await tokenAccounts(ctx,[s.a,s.b],remove?[0,0]:limits,request.parameters?.wrapSol===true);
 const options={poolInfo:data.poolInfo,poolKeys:data.poolKeys,ownerInfo:{wallet:ctx.owner,tokenAccountA:accounts.addresses[0],tokenAccountB:accounts.addresses[1]},liquidity:new BN(quote.details.liquidity)};
 let built,signers=[];
 if(request.position){
  const p=await position(ctx,request.position,quote.pool),nft=await mint(ctx,p.data.nftMint);options.nft2022=nft.programId===TOKEN_2022_PROGRAM_ID.toBase58();
  if(remove){
   const rewardMints=await Promise.all(data.poolKeys.rewardInfos.map(r=>mint(ctx,r.mint.address)));
   const rewards=await tokenAccounts(ctx,rewardMints,rewardMints.map(()=>0),false);accounts.instructions.push(...rewards.instructions);accounts.cleanup.push(...rewards.cleanup);accounts.signers.push(...rewards.signers);
   built=ClmmInstrument.decreaseLiquidityInstructions({...options,ownerInfo:{...options.ownerInfo,rewardAccounts:rewards.addresses},ownerPosition:p.data,amountMinA:limits[0],amountMinB:limits[1]});
  }else built=ClmmInstrument.increasePositionFromLiquidityInstructions({...options,ownerPosition:p.data,amountMaxA:limits[0],amountMaxB:limits[1]});
  // SDK derives the owner's ATA for position authorization. Require it explicitly.
  if(!built.instructions.some(ix=>ix.keys.some(k=>k.pubkey.equals(p.tokenAccount))))throw new Error('Position NFT must be in the wallet associated token account for this Raydium instruction');
 }else{
  const nft=retained(ctx,quote.pool);if(nft.publicKey.toBase58()!==quote.details.positionMint)throw new Error('Position signer expired');
  built=await ClmmInstrument.openPositionFromLiquidityInstructions({...options,tickLower:quote.details.tickLowerIndex,tickUpper:quote.details.tickUpperIndex,amountMaxA:limits[0],amountMaxB:limits[1],base:null,withMetadata:'no-create',getEphemeralSigners:async n=>{if(n!==1)throw new Error('Unexpected SDK signer request');return[nft.publicKey.toBase58()];}});signers=[nft];
 }
 return{pool:quote.pool,position:quote.position,transactions:[{instructions:[...accounts.instructions,...built.instructions,...(built.endInstructions??[]),...accounts.cleanup],signers:[...accounts.signers,...built.signers,...signers]}]};
 }
};
export default raydiumClmm;
