#!/usr/bin/env python3
"""Generate the compiled adapter registry from declarative manifests. No plugin code is run."""
import argparse, json, re
from pathlib import Path

IDENT = re.compile(r'^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$')
TYPE = re.compile(r'^[A-Z][A-Za-z0-9]*$')
KINDS = {'swap', 'add-liquidity', 'remove-liquidity', 'stake', 'unstake', 'wrap', 'unwrap'}

def manifests(root):
    result = []
    for path in sorted((root/'adapters').glob('*.json')):
        if path.is_symlink(): raise ValueError('symlink manifest')
        data = json.loads(path.read_text())
        if set(data) != {'id','crate','type','operations','requiresConfiguration','provenance'}:
            raise ValueError(f'{path.name}: unexpected/missing fields')
        name = data['id']
        if not isinstance(name,str) or not IDENT.fullmatch(name) or path.stem != name:
            raise ValueError('invalid adapter id')
        if data['crate'] != 'dex-'+name or not TYPE.fullmatch(data['type']):
            raise ValueError('invalid adapter crate/type')
        if type(data['requiresConfiguration']) is not bool:
            raise ValueError('requiresConfiguration must be boolean')
        if not data['operations'] or len(set(data['operations'])) != len(data['operations']) or not set(data['operations']) <= KINDS:
            raise ValueError('invalid operations')
        p=data['provenance']
        if not isinstance(p,dict) or set(p)!={'source','revision','license'} or not all(isinstance(v,str) and v.strip() for v in p.values()):
            raise ValueError('source, revision and license are required')
        crate=root/'lib'/data['crate']
        if crate.is_symlink() or not (crate/'Cargo.toml').is_file():
            raise ValueError('missing adapter crate')
        result.append(data)
    return result

def generate(root, check=False):
    entries=manifests(root)
    cargo='''# Generated by tools/registry/generate.py; edit adapters/*.json instead.
[package]
name = "adapter-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
router-lib = { path = "../router-lib" }
router-feed-lib = { path = "../router-feed-lib" }
'''
    code='''// Generated by tools/registry/generate.py. Do not edit.
use std::{collections::HashMap, sync::Arc};
use router_lib::dex::DexInterface;
use router_feed_lib::router_rpc_client::RouterRpcClient;

pub async fn initialize(
    rpc: &mut RouterRpcClient,
    configured: &HashMap<String, HashMap<String, String>>,
    disabled: &[String],
) -> anyhow::Result<Vec<Arc<dyn DexInterface>>> {
    let mut adapters = Vec::new();
'''
    for e in entries:
        cargo+=f'{e["crate"]} = {{ path = "../{e["crate"]}" }}\n'
        condition=f'!disabled.iter().any(|id| id == "{e["id"]}")'
        if e['requiresConfiguration']: condition+=f' && configured.contains_key("{e["id"]}")'
        code+=f'''    if {condition} {{
        adapters.push({e['crate'].replace('-','_')}::{e['type']}::initialize(
            rpc, configured.get("{e['id']}").cloned().unwrap_or_default(),
        ).await?);
    }}
'''
    code+='    Ok(adapters)\n}\n'
    code+='\npub async fn initialize_one(id: &str, rpc: &mut RouterRpcClient, options: HashMap<String, String>) -> anyhow::Result<Arc<dyn DexInterface>> {\n    match id {\n'
    for e in entries:
        code+=f'        "{e["id"]}" => {e["crate"].replace("-","_")}::{e["type"]}::initialize(rpc, options).await,\n'
    code+='        _ => anyhow::bail!("Unknown adapter: {}", id),\n    }\n}\n' 
    files={root/'lib/adapter-registry/Cargo.toml':cargo,root/'lib/adapter-registry/src/lib.rs':code}
    for path, content in files.items():
        if check:
            if not path.exists() or path.read_text()!=content: raise ValueError(f'stale generated registry: {path}')
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    return entries

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[2]);parser.add_argument('--check',action='store_true')
    args=parser.parse_args();generate(args.root.resolve(),args.check)
