import test from 'node:test';
import assert from 'node:assert/strict';
import { Keypair, SystemProgram, TransactionInstruction, PublicKey } from '@solana/web3.js';
import { getTransactionDecoder } from '@solana/kit';
import { createPublicKey, verify } from 'node:crypto';
import { LiquidityEngine, enforceApprovedBounds } from '../engine.mjs';
import { compileOperation } from '../transactions.mjs';
const owner=Keypair.generate(),other=Keypair.generate(),pool=Keypair.generate().publicKey.toBase58();
const mint=Keypair.generate().publicKey.toBase58();
const lifetime={blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:123456};
const debit=(expected='100',limit='105')=>({mint,decimals:6,expectedRaw:expected,limitRaw:limit,direction:'debit'});
const quote=(amounts=[debit()])=>({pool,amounts,slot:100});
const req={owner:owner.publicKey.toBase58(),venue:'test',operation:'add',slippageBps:50,transactionVersion:'1'};
const instruction=()=>SystemProgram.transfer({fromPubkey:owner.publicKey,toPubkey:other.publicKey,lamports:100});
test('fresh price may improve but cannot widen a reviewed debit or lower credit',()=>{
 const approved={...quote(),operation:'add'};
 assert.deepEqual(enforceApprovedBounds(approved,quote([debit('104','110')])),approved);
 assert.throws(()=>enforceApprovedBounds(approved,quote([debit('106','111')])),/approved limits/);
 const credit={...debit('100','95'),direction:'credit'};
 assert.throws(()=>enforceApprovedBounds({...quote([credit]),operation:'remove'},quote([{...credit,expectedRaw:'94',limitRaw:'90'}])),/approved limits/);
 assert.throws(()=>enforceApprovedBounds(approved,{...quote(),pool:mint}),/identity/);
 assert.throws(()=>enforceApprovedBounds(approved,quote([{...debit(),mint:pool}])),/tokens/);
});
test('owner, expiry and version remain bound to server quote; builder gets original limits',async()=>{
 let now=1000,seen;
 const adapter={id:'test',capabilities:['add'],parameters:{},quote:async()=>quote(),build:async(_c,_r,q)=>{seen=q;return {pool,transactions:[{instructions:[instruction()]}]};}};
 const engine=new LiquidityEngine({connection:{getLatestBlockhash:async()=>lifetime},adapters:[adapter],now:()=>now});
 const original=await engine.quote(req);
 await assert.rejects(()=>engine.build({quoteId:original.quoteId,owner:other.publicKey.toBase58(),transactionVersion:'1'}),/another wallet/);
 await assert.rejects(()=>engine.build({quoteId:original.quoteId,owner:req.owner,transactionVersion:'0'}),/version/);
 adapter.quote=async()=>quote([debit('102','108')]);
 const built=await engine.build({quoteId:original.quoteId,owner:req.owner,transactionVersion:'1',amounts:[debit('999','999')]});
 assert.deepEqual(seen,original);assert.equal(built.transactions.length,1);
 now=original.expiresAt;
 await assert.rejects(()=>engine.build({quoteId:original.quoteId,owner:req.owner,transactionVersion:'1'}),/expired/);
});
test('empty economics are only allowed for native pool initialization',async()=>{
 const adapter={id:'test',capabilities:['initialize','add'],quote:async()=>quote([])};
 const engine=new LiquidityEngine({connection:{},adapters:[adapter]});
 await assert.rejects(()=>engine.quote(req),/economic quote/);
 assert.equal((await engine.quote({...req,operation:'initialize'})).amounts.length,0);
});
test('V1 has correct payer, resources and valid ephemeral signatures independent of wallet',()=>{
 const position=Keypair.generate();
 const ix=SystemProgram.createAccount({fromPubkey:owner.publicKey,newAccountPubkey:position.publicKey,space:1,lamports:100,programId:SystemProgram.programId});
 const built=compileOperation({instructions:[ix],signers:[position]},owner.publicKey,lifetime,'1');
 const tx=getTransactionDecoder().decode(Buffer.from(built.transaction,'base64'));
 assert.deepEqual(built.expectedSigners,[owner.publicKey.toBase58(),position.publicKey.toBase58()]);
 const key=createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),position.publicKey.toBuffer()]),format:'der',type:'spki'});
 assert.equal(verify(null,tx.messageBytes,key,tx.signatures[position.publicKey.toBase58()]),true);
 assert.equal(tx.signatures[owner.publicKey.toBase58()],null);
 assert.equal(tx.messageBytes[0],0x81);
});
test('missing signer, oversized V0 and implicit version downgrade are rejected',()=>{
 const position=Keypair.generate();
 const ix=SystemProgram.createAccount({fromPubkey:owner.publicKey,newAccountPubkey:position.publicKey,space:1,lamports:100,programId:SystemProgram.programId});
 assert.throws(()=>compileOperation({instructions:[ix]},owner.publicKey,lifetime,'1'),/Missing required/);
 assert.throws(()=>compileOperation({instructions:[instruction()],signers:[owner]},owner.publicKey,lifetime,'1'),/never sign/);
 const big=new TransactionInstruction({programId:new PublicKey(mint),keys:[],data:Buffer.alloc(1400)});
 assert.equal(compileOperation({instructions:[big]},owner.publicKey,lifetime,'1').transactionVersion,'1');
 assert.throws(()=>compileOperation({instructions:[big]},owner.publicKey,lifetime,'0'));
});
