// Generated by tools/registry/generate.py. Do not edit.
use std::{collections::HashMap, sync::Arc};
use router_lib::dex::DexInterface;
use router_feed_lib::router_rpc_client::RouterRpcClient;

pub async fn initialize(
    rpc: &mut RouterRpcClient,
    configured: &HashMap<String, HashMap<String, String>>,
    disabled: &[String],
) -> anyhow::Result<Vec<Arc<dyn DexInterface>>> {
    let mut adapters = Vec::new();
    if !disabled.iter().any(|id| id == "meteora-dbc") {
        adapters.push(dex_meteora_dbc::MeteoraDbcDex::initialize(
            rpc, configured.get("meteora-dbc").cloned().unwrap_or_default(),
        ).await?);
    }
    if !disabled.iter().any(|id| id == "stake-pool") && configured.contains_key("stake-pool") {
        adapters.push(dex_stake_pool::StakePoolDex::initialize(
            rpc, configured.get("stake-pool").cloned().unwrap_or_default(),
        ).await?);
    }
    Ok(adapters)
}

pub async fn initialize_one(id: &str, rpc: &mut RouterRpcClient, options: HashMap<String, String>) -> anyhow::Result<Arc<dyn DexInterface>> {
    match id {
        "meteora-dbc" => dex_meteora_dbc::MeteoraDbcDex::initialize(rpc, options).await,
        "stake-pool" => dex_stake_pool::StakePoolDex::initialize(rpc, options).await,
        _ => anyhow::bail!("Unknown adapter: {}", id),
    }
}
